### PR TITLE
Added Round Newpipe Icon

### PR DESCRIPTION
**Pull request by connectety**
I created a round SVG, because I dislike some stuff of the "sticker_52x52.svg" and want to offer an alternative.
It should not be too hard to replace the circle, if any other shape is wanted.
To do this just replace the circle in the group named "Shape" with a path, which forms any shape wanted.
(Some off the relative positions of the WhiteIcon-path might be off by a bit)

### CODE REVIEW

**Comment by TheAssassin** [comment]
I was about to comment.

This is a merch repo, i.e., it hall only contain media that can be used to make merchandise. It's not a general media repository.

Your icon lacks the white margin that might serve very useful even for round stickers as it creates some contrast between the icon and a background.

Also, you titled your file "icon", but you put it in the "sticker" directory. That doesn't make _any_ sense at all.

We should've talked about whether to allow icons without the white margin at all anyway @theScrabi.

Then, there's a license issue: noone has talked about how this file is to be licensed and who needs to be credited for it.

This should be reverted ASAP.

**Comment by connectety** [comment]
> you titled your file "icon", but you put it in the "sticker" directory.

I created this icon to make stickers out of it (one of the two reasons, it is in the sticker folder) and the file title itself does not contain the word icon.


> noone has talked about how this file is to be licensed and who needs to be credited for it.

I created the file by hand but occasionally took to "sticker_52x52.svg" for help.
Whether it is my own creation or a "remix" of the existing sticker it should probably be licensed under the same license as the other sticker for simplicity.
That is the other reason why this file is in the sticker folder

> Your icon lacks the white margin

I will add this if specifically ask for, but for now, I did not add this as the app icon does not have this either.


Sorry for the inconvinience.

**Comment by TheAssassin** [comment]
@connectety that helps clarify a few points.

What is the size of your stickers? I want to standardize that, hence there's a length/width in the filename of the sticker.

**Comment by connectety** [comment]
I would like to suggest 55mm for length and height.

**Comment by TheAssassin** [comment]
I guess you would also not mind if we rename and/or replace the icon with one with the white margin?

@TobiGr what do you think: is the white circle essential? IMO it's very useful for better contrast e.g., on laptop lids.

**Comment by TheAssassin** [comment]
Regarding your sticker, @connectety, one criticism about the original sticker was that it lacks information and just contains the name and logo, not a URL to a website or anything. That problem has been worsened here (sounds harsh, but kind of what we've been worried about last time). We should discuss that, too. I guess we need to put some guidelines for making stickers in the repository.

**Pull request merged**
